# Config for q2 integrasjoner

TOKEN_X_WELL_KNOWN_URL: https://tokenx.dev-gcp.nav.cloud.nais.io/.well-known/oauth-authorization-server
TOKEN_X_CLIENT_ID: dev-gcp:teammelosys:melosys-skjema-api
TOKEN_X_TOKEN_ENDPOINT: https://tokenx.dev-gcp.nav.cloud.nais.io/token
TOKENX_AUDIENCE_ARBEIDSGIVER_ALTINN_TILGANGER: dev-gcp:fager:arbeidsgiver-altinn-tilganger
ALTINN_RESSURS: test-fager
ARBEIDSGIVER_ALTINN_TILGANGER_URL: https://arbeidsgiver-altinn-tilganger.intern.dev.nav.no
TOKENX_AUDIENCE_ARBEIDSGIVER_NOTIFIKASJON: test:fager:arbeidsgiver-notifikasjon
KAFKA_BROKERS: unused-in-local-q2
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.kafka.autoconfigure.KafkaAutoConfiguration
FLYWAY_ENABLED: false
NAIS_CLUSTER_NAME: dev-gcp
NAIS_NAMESPACE: teammelosys
NAIS_APP_NAME: melosys-skjema-api
ARBEIDSGIVER_NOTIFIKASJON_URL: https://notifikasjon-fake-produsent-api.ekstern.dev.nav.no
MERKELAPP: test-fager
RESSURS_ID: test-fager
SERVER_PORT: 8090
EREG_URL: https://ereg-services.intern.dev.nav.no
BRUK_SYNTETISK_FNR: true
VARSLING_ARBEIDSTAKER_SKJEMA_LENKE: https://melosys-skjema-web.intern.dev.nav.no
REPR_URL: https://repr-api.intern.dev.nav.no
REPR_CACHE_TTL_MINUTES: 0
TOKENX_AUDIENCE_REPR: dev-gcp:repr:repr-api
PDL_URL: https://pdl-api.dev.intern.nav.no/graphql
PDL_SCOPE: api://dev-fss.pdl.pdl-api/.default
AZURE_OPENID_CONFIG_TOKEN_ENDPOINT: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token
AZURE_APP_WELL_KNOWN_URL: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
MELOSYS_CLIENT_ID: placeholder-melosys-client-id
KAFKA_SKJEMA_MOTTAK_TOPIC: teammelosys.skjema.innsendt.q2-local
KAFKA_BRUKERVARSEL_TOPIC: min-side.aapen-brukervarsel-v1
VEDLEGG_BUCKET_NAME: melosys-skjema-vedlegg-local
CLAMAV_URL: http://not-used-in-local

kubernetes:
  azure:
    kubectl:
      path: ${KUBECTL_PATH:/usr/local/bin}
    kubelogin:
      path: ${KUBELOGIN_PATH:/home/linuxbrew/.linuxbrew/bin}
    gcloud:
      path: ${GCLOUD_PATH}
