name: Publish Types (Java 21)

on:
  push:
    branches:
      - main
    paths:
      - 'melosys-skjema-api-types/**'
      - '.github/workflows/publish-types*.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    uses: ./.github/workflows/publish-types.yml
    with:
      java-version: '21'
      version-suffix: ''
